Repository ChanMinLee2/UNIX_Project, pull requests merged in 2024-12, with the labels that each got.

#3 ✨ [Feat] TicTacToe 게임 기록 저장 기능 구현
  .gitignore
  project/history.txt
  project/server.c
Labels: ✨feature

#5 ♻️ [Refactor] 필요 없는 코드 삭제 혹은 주석 처리
  project/client.c
  project/server.c
Labels: ♻️refactor

#6 🚀[Chore] TicTacToe 게임 merge로 통합
  .gitignore
  project/client.c
  project/history.txt
  project/makefile
  project/server.c
Labels: 🚀chore
